# 参考↓
# https://hub.docker.com/_/golang
FROM golang:1.19.4-alpine3.16

ENV ROOT=/go

WORKDIR ${ROOT}

# gitをインストールします。
# RUN apt update && apk add git

# main.goを/go/src/appにコピーします。
COPY . .

# go mod tidyを実行します。
RUN go mod tidy

RUN go build -o app main.go
