FROM mysql:latest

COPY mysql/sql/ /docker-entrypoint-initdb.d/01_create_db.sql
COPY mysql/conf.d/ //etc/mysql/conf.d/01_create_db.cnf

RUN chmod 644 /etc/mysql/conf.d/my.cnf

CMD ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
